name: deploy workflow to dev

on: 
  push:
    branches:
      - dev  # Trigger when code is pushed (e.g., merged) into 'dev'
  workflow_dispatch:  # Optional manual trigger

jobs:
  deploy-to-databricks:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets.DEPLOYMENT_TARGET_URL }}
      DATABRICKS_TOKEN: ${{ secrets.DEPLOYMENT_TARGET_TOKEN }}
      REPO_PATH: /Workspace/Repos/tetris-dev/databrick-cicd

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - uses: databricks/setup-cli@main

      - name: Get branch name
        id: get_branch
        run: echo "branch=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Update Databricks Git folder
        run: |
          echo "Updating Databricks repo to branch: ${{ steps.get_branch.outputs.branch }}"
          databricks repos update ${{ env.REPO_PATH }} --branch "${{ steps.get_branch.outputs.branch }}"
